### ISSUE TITLE
cat! i'm a kitty cat

### ISSUE THREAD

**Issue by crygup** [razyness/catness#1]
cat! i'm a kitty cat
and i dance, dance, dance and i dance, dance, dance

cat? i'm a kitty cat!
and i dance, dance, dance and i dance, dance, dance

cat? i'm a kitty cat!
and i dance, dance, dance and i dance, dance, dance

cat! i'm a kitty cat!
and i dance, dance, dance and i dance, dance, dance
cat? i'm a kitty cat!
and i dance, dance, dance and i dance, dance, dance

cat! i'm a kitty cat!
and i dance, dance, dance and i dance, dance, dance

provocative posing!
provocative posing!

cat! i'm a [chiquita]!
and i meow, meow, meow and i meow, meow, meow

cat? i'm a kitty cat
and i meow, meow, meow and i meow, meow, meow

cat! i'm a kitty cat!
and i dance, dance, dance, da-da-dance, dance, dance

cat?! i'm a kitty cat!
and i dance, dance, dance and i dance, dance, dance

i say sexy things to myself while i'm da-ancing

i say sexy things to myself while i'm da-ancing

provocative posing!
provocative posing!

cat! i'm a pitty pat!
and i poo, poo, poo, peedee, dee, pah pah

cat! i'm the kitty cat!
and i meow, meow, meow and i meow, meow, meow

cat? i'm a kitty cat!
and i dance, dance, dance and i dance, dance, dance

cat? i'm the kitty cat!
and i meow, meow, meow and i meow, meow, meow

cat. i'm a kitty cat!
and i dance, dance, dance and i dance, dance, dance

**Comment by razyness** [comment]
![EMzFFog](https://user-images.githubusercontent.com/97766343/211787551-995d05fe-2f3b-4342-a1af-85e8e8523f9b.jpg)
